export { default as About } from './About/About'
export { default as Blog } from './Blog/Blog'
export { default as Feedback } from './Feedback/Feedback'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Services } from './Services/Services'
export { default as University } from './University/University'
export { default as Back } from './Back/Back'